name: call_slider_button
description: A customizable Flutter widget mimicking a call slider button.
version: 1.1.0
repository: https://github.com/OmerJahangir/call_slider_button

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.8.0

dev_dependencies:

  lints: ^5.0.0
  test: ^1.24.0

screenshots:
  - path: screenshots/demo1.gif
    description: Slide to accept the call
  - path: screenshots/demo2.gif
    description: Slide to decline the call